name: Build Status

on: 
 push:
 pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install
      run: |
       sudo apt-get install -y -qq lcov
       sudo apt-get install texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-latex-extra
      

    - name: Compile using Cmake
      run: |
        export CXX=g++-9
        mkdir build
        cd build
        cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ../
        make
        make code_coverage
        test/code_test

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@1.1.3
      with:
        path-to-lcov: ${{ github.workspace }}/build/coverage.info.cleaned
        github-token: ${{ secrets.GITHUB_TOKEN }}
