name: Build Status

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Before Install
      run: pip install --user cpp-coveralls 

    - name: Install
      run: sudo apt-get install -y -qq lcov

    - name: Compile using Cmake
      run: |
        export CXX=g++-9
        mkdir build
        cd build
        cmake -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ../
        make
        make code_coverage
        test/code_test
        
    - name: Generate coveralls file
      run: coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*" -E".*app/main.cpp" -E ".*vendor/*" -E ".*include/Eigen*" -t iL0KsC5KmT4QDXQvQBEzi96WnqSImO5sQ
